<?php
$tbf_info = array();
$tab_info = array();
$role_info = array();
include('previleges/table/previleges_crm_table_crm_channel.php');
include('previleges/table/previleges_crm_table_crm_customer.php');
include('previleges/table/previleges_crm_table_crm_employee.php');
include('previleges/table/previleges_crm_table_crm_emp_request.php');
include('previleges/table/previleges_crm_table_crm_orgunit.php');
include('previleges/table/previleges_crm_table_customer_type.php');

include('previleges/table/previleges_crm_table_request.php');
include('previleges/table/previleges_crm_table_request_file.php');
include('previleges/table/previleges_crm_table_request_prio.php');
include('previleges/table/previleges_crm_table_request_status.php');
include('previleges/table/previleges_crm_table_request_type.php');
include('previleges/table/previleges_crm_table_response.php');
include('previleges/table/previleges_crm_table_response_data.php');
include('previleges/table/previleges_crm_table_response_template.php');
include('previleges/table/previleges_crm_table_response_type.php');
include('previleges/table/previleges_crm_table_servic.php');
include('previleges/table/previleges_crm_table_service_category.php');
include('previleges/table/previleges_crm_table_survey.php');
include('previleges/table/previleges_crm_table_survey_token.php');
include('previleges/role/previleges_crm_role322.php');
include('previleges/role/previleges_crm_role347.php');
include('previleges/role/previleges_crm_role323.php');
include('previleges/role/previleges_crm_role317.php');
include('previleges/role/previleges_crm_role324.php');
include('previleges/role/previleges_crm_role327.php');
include('previleges/role/previleges_crm_role376.php');
include('previleges/role/previleges_crm_role375.php');
include('previleges/role/previleges_crm_role115.php');
