<?php

	$role_info[322] = array (
  'code' => 'goal-CRM-DATA',
  'name' => 
  array (
    'ar' => 'إدارة المنتج',
    'en' => 'product admin',
  ),
  'menu' => 
  array (
    'need_admin' => false,
    'id' => '322',
    'menu_name_ar' => 'إدارة المنتج',
    'menu_name_en' => 'product admin',
    'page' => 'main.php?Main_Page=fm.php&a=1073&r=322',
    'css' => 'info',
    'icon' => ' icon-322',
    'showme' => true,
    'items' => 
    array (
      103898 => 
      array (
        'id' => '103898',
        'code' => 'f1-a-tb3570/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة حالات الطلبات الالكترونية',
        'menu_name_en' => 'Request statuss administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=RequestStatus&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103898 bfc-',
      ),
      103908 => 
      array (
        'id' => '103908',
        'code' => 'f1-a-tb3572/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة أنواع الأجوبة',
        'menu_name_en' => 'Media response types administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=ResponseType&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103908 bfc-',
      ),
      103944 => 
      array (
        'id' => '103944',
        'code' => 'f1-a-tb3579/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء سياسة متابعة',
        'menu_name_en' => 'create Crm action policy',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=ActionPolicy&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103944 bfc-',
      ),
      103949 => 
      array (
        'id' => '103949',
        'code' => 'f1-a-tb3579/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن سياسة متابعة',
        'menu_name_en' => 'Crm action policy quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ActionPolicy&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103949 bfc-',
      ),
      104208 => 
      array (
        'id' => '104208',
        'code' => 'f1-a-tb3580/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة اجراءات خدمة العملاء',
        'menu_name_en' => 'Crm actions administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=CrmAction&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-104208 bfc-',
      ),
      103923 => 
      array (
        'id' => '103923',
        'code' => 'f1-a-tb3611/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن خدمة',
        'menu_name_en' => 'Service quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Service&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103923 bfc-',
      ),
      103929 => 
      array (
        'id' => '103929',
        'code' => 'f1-a-tb3612/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن صنف خدمة',
        'menu_name_en' => 'Service category quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ServiceCategory&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103929 bfc-',
      ),
      104197 => 
      array (
        'id' => '104197',
        'code' => 'f1-a-tb3621/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن مدينة',
        'menu_name_en' => 'Acity quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Acity&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104197 bfc-',
      ),
      104205 => 
      array (
        'id' => '104205',
        'code' => 'f1-a-tb3622/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة المناطق',
        'menu_name_en' => 'Aregions administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=Aregion&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-104205 bfc-',
      ),
      104198 => 
      array (
        'id' => '104198',
        'code' => 'f1-a-tb3623/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء acountry.single',
        'menu_name_en' => 'create Acountry',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Acountry&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104198 bfc-',
      ),
      104203 => 
      array (
        'id' => '104203',
        'code' => 'f1-a-tb3623/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن acountry.single',
        'menu_name_en' => 'Acountry quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Acountry&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104203 bfc-',
      ),
      103219 => 
      array (
        'id' => '103219',
        'code' => 'f1-a-tb13455/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة أنواع الطلبات الالكترونية',
        'menu_name_en' => 'Crm erequest types administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=RequestType&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103219 bfc-',
      ),
      103239 => 
      array (
        'id' => '103239',
        'code' => 'f1-a-tb13459/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء مسار طلب الكتروني',
        'menu_name_en' => 'create Crm erequest path',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=RequestPath&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103239 bfc-',
      ),
      103244 => 
      array (
        'id' => '103244',
        'code' => 'f1-a-tb13459/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن مسار طلب الكتروني',
        'menu_name_en' => 'Crm erequest path quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=RequestPath&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103244 bfc-',
      ),
      103252 => 
      array (
        'id' => '103252',
        'code' => 'f1-a-tb13464/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء برنامج خدمة العملاء',
        'menu_name_en' => 'create Crm sh params',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Program&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103252 bfc-',
      ),
      103257 => 
      array (
        'id' => '103257',
        'code' => 'f1-a-tb13464/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن برنامج خدمة العملاء',
        'menu_name_en' => 'Crm sh params quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Program&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103257 bfc-',
      ),
    ),
    'otherbfs' => 
    array (
      103219 => 
      array (
        'id' => '103219',
        'code' => 'f1-a-tb13455/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة أنواع الطلبات الالكترونية',
        'menu_name_en' => 'Crm erequest types administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=RequestType&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103219 bfc-',
      ),
      103220 => 
      array (
        'id' => '103220',
        'code' => 'f1-a-tb13455/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح نوع طلب الكتروني',
        'menu_name_en' => 'delete Crm erequest type',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=RequestType&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103220 bfc-',
      ),
      103221 => 
      array (
        'id' => '103221',
        'code' => 'f1-a-tb13455/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل نوع طلب الكتروني',
        'menu_name_en' => 'display details of Crm erequest type',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=RequestType&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103221 bfc-',
      ),
      103239 => 
      array (
        'id' => '103239',
        'code' => 'f1-a-tb13459/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء مسار طلب الكتروني',
        'menu_name_en' => 'create Crm erequest path',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=RequestPath&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103239 bfc-',
      ),
      103240 => 
      array (
        'id' => '103240',
        'code' => 'f1-a-tb13459/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة مسارات الطلبات الالكترونية',
        'menu_name_en' => 'Crm erequest paths administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=RequestPath&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103240 bfc-',
      ),
      103241 => 
      array (
        'id' => '103241',
        'code' => 'f1-a-tb13459/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح مسار طلب الكتروني',
        'menu_name_en' => 'delete Crm erequest path',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=RequestPath&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103241 bfc-',
      ),
      103242 => 
      array (
        'id' => '103242',
        'code' => 'f1-a-tb13459/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل مسار طلب الكتروني',
        'menu_name_en' => 'display details of Crm erequest path',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=RequestPath&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103242 bfc-',
      ),
      103243 => 
      array (
        'id' => '103243',
        'code' => 'f1-a-tb13459/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في مسارات الطلبات الالكترونية',
        'menu_name_en' => 'Crm erequest paths search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=RequestPath&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103243 bfc-',
      ),
      103244 => 
      array (
        'id' => '103244',
        'code' => 'f1-a-tb13459/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن مسار طلب الكتروني',
        'menu_name_en' => 'Crm erequest path quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=RequestPath&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103244 bfc-',
      ),
      103245 => 
      array (
        'id' => '103245',
        'code' => 'f1-a-tb13459/stats',
        'level' => '999',
        'menu_name_ar' => 'إجراء إحصائيات حول مسارات الطلبات الالكترونية',
        'menu_name_en' => 'Crm erequest paths statistics',
        'page' => 'main.php?Main_Page=afw_mode_stats.php&cl=RequestPath&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103245 bfc-',
      ),
      103252 => 
      array (
        'id' => '103252',
        'code' => 'f1-a-tb13464/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء برنامج خدمة العملاء',
        'menu_name_en' => 'create Crm sh params',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Program&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103252 bfc-',
      ),
      103253 => 
      array (
        'id' => '103253',
        'code' => 'f1-a-tb13464/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة برامج خدمات العملاء',
        'menu_name_en' => 'Crm sh paramss administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=Program&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103253 bfc-',
      ),
      103254 => 
      array (
        'id' => '103254',
        'code' => 'f1-a-tb13464/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح برنامج خدمة العملاء',
        'menu_name_en' => 'delete Crm sh params',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Program&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103254 bfc-',
      ),
      103255 => 
      array (
        'id' => '103255',
        'code' => 'f1-a-tb13464/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل برنامج خدمة العملاء',
        'menu_name_en' => 'display details of Crm sh params',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Program&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103255 bfc-',
      ),
      103256 => 
      array (
        'id' => '103256',
        'code' => 'f1-a-tb13464/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في برامج خدمات العملاء',
        'menu_name_en' => 'Crm sh paramss search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Program&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103256 bfc-',
      ),
      103257 => 
      array (
        'id' => '103257',
        'code' => 'f1-a-tb13464/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن برنامج خدمة العملاء',
        'menu_name_en' => 'Crm sh params quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Program&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103257 bfc-',
      ),
      103258 => 
      array (
        'id' => '103258',
        'code' => 'f1-a-tb13464/stats',
        'level' => '999',
        'menu_name_ar' => 'إجراء إحصائيات حول برامج خدمات العملاء',
        'menu_name_en' => 'Crm sh paramss statistics',
        'page' => 'main.php?Main_Page=afw_mode_stats.php&cl=Program&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103258 bfc-',
      ),
      103898 => 
      array (
        'id' => '103898',
        'code' => 'f1-a-tb3570/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة حالات الطلبات الالكترونية',
        'menu_name_en' => 'Request statuss administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=RequestStatus&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103898 bfc-',
      ),
      103899 => 
      array (
        'id' => '103899',
        'code' => 'f1-a-tb3570/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح حالة طلب إلكتروني',
        'menu_name_en' => 'delete Request status',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=RequestStatus&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103899 bfc-',
      ),
      103900 => 
      array (
        'id' => '103900',
        'code' => 'f1-a-tb3570/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل حالة طلب إلكتروني',
        'menu_name_en' => 'display details of Request status',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=RequestStatus&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103900 bfc-',
      ),
      103908 => 
      array (
        'id' => '103908',
        'code' => 'f1-a-tb3572/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة أنواع الأجوبة',
        'menu_name_en' => 'Media response types administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=ResponseType&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103908 bfc-',
      ),
      103909 => 
      array (
        'id' => '103909',
        'code' => 'f1-a-tb3572/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح نوع إجابة',
        'menu_name_en' => 'delete Media response type',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=ResponseType&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103909 bfc-',
      ),
      103910 => 
      array (
        'id' => '103910',
        'code' => 'f1-a-tb3572/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل نوع إجابة',
        'menu_name_en' => 'display details of Media response type',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=ResponseType&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103910 bfc-',
      ),
      103918 => 
      array (
        'id' => '103918',
        'code' => 'f1-a-tb3611/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء خدمة',
        'menu_name_en' => 'create Service',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Service&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103918 bfc-',
      ),
      103919 => 
      array (
        'id' => '103919',
        'code' => 'f1-a-tb3611/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة الخدمات',
        'menu_name_en' => 'Services administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=Service&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103919 bfc-',
      ),
      103920 => 
      array (
        'id' => '103920',
        'code' => 'f1-a-tb3611/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح خدمة',
        'menu_name_en' => 'delete Service',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Service&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103920 bfc-',
      ),
      103921 => 
      array (
        'id' => '103921',
        'code' => 'f1-a-tb3611/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل خدمة',
        'menu_name_en' => 'display details of Service',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Service&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103921 bfc-',
      ),
      103922 => 
      array (
        'id' => '103922',
        'code' => 'f1-a-tb3611/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في الخدمات',
        'menu_name_en' => 'Services search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Service&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103922 bfc-',
      ),
      103923 => 
      array (
        'id' => '103923',
        'code' => 'f1-a-tb3611/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن خدمة',
        'menu_name_en' => 'Service quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Service&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103923 bfc-',
      ),
      103924 => 
      array (
        'id' => '103924',
        'code' => 'f1-a-tb3612/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء صنف خدمة',
        'menu_name_en' => 'create Service category',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=ServiceCategory&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103924 bfc-',
      ),
      103925 => 
      array (
        'id' => '103925',
        'code' => 'f1-a-tb3612/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة أصناف الخدمات',
        'menu_name_en' => 'Service categorys administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=ServiceCategory&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103925 bfc-',
      ),
      103926 => 
      array (
        'id' => '103926',
        'code' => 'f1-a-tb3612/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح صنف خدمة',
        'menu_name_en' => 'delete Service category',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=ServiceCategory&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103926 bfc-',
      ),
      103927 => 
      array (
        'id' => '103927',
        'code' => 'f1-a-tb3612/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل صنف خدمة',
        'menu_name_en' => 'display details of Service category',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=ServiceCategory&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103927 bfc-',
      ),
      103928 => 
      array (
        'id' => '103928',
        'code' => 'f1-a-tb3612/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في أصناف الخدمات',
        'menu_name_en' => 'Service categorys search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=ServiceCategory&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103928 bfc-',
      ),
      103929 => 
      array (
        'id' => '103929',
        'code' => 'f1-a-tb3612/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن صنف خدمة',
        'menu_name_en' => 'Service category quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ServiceCategory&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103929 bfc-',
      ),
      103944 => 
      array (
        'id' => '103944',
        'code' => 'f1-a-tb3579/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء سياسة متابعة',
        'menu_name_en' => 'create Crm action policy',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=ActionPolicy&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103944 bfc-',
      ),
      103945 => 
      array (
        'id' => '103945',
        'code' => 'f1-a-tb3579/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة سياسات متابعة تغير حالات الطلبات',
        'menu_name_en' => 'Crm action policys administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=ActionPolicy&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103945 bfc-',
      ),
      103946 => 
      array (
        'id' => '103946',
        'code' => 'f1-a-tb3579/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح سياسة متابعة',
        'menu_name_en' => 'delete Crm action policy',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=ActionPolicy&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103946 bfc-',
      ),
      103947 => 
      array (
        'id' => '103947',
        'code' => 'f1-a-tb3579/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل سياسة متابعة',
        'menu_name_en' => 'display details of Crm action policy',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=ActionPolicy&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103947 bfc-',
      ),
      103948 => 
      array (
        'id' => '103948',
        'code' => 'f1-a-tb3579/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في سياسات متابعة تغير حالات الطلبات',
        'menu_name_en' => 'Crm action policys search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=ActionPolicy&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103948 bfc-',
      ),
      103949 => 
      array (
        'id' => '103949',
        'code' => 'f1-a-tb3579/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن سياسة متابعة',
        'menu_name_en' => 'Crm action policy quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ActionPolicy&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103949 bfc-',
      ),
      103950 => 
      array (
        'id' => '103950',
        'code' => 'f1-a-tb3579/stats',
        'level' => '999',
        'menu_name_ar' => 'إجراء إحصائيات حول سياسات متابعة تغير حالات الطلبات',
        'menu_name_en' => 'Crm action policys statistics',
        'page' => 'main.php?Main_Page=afw_mode_stats.php&cl=ActionPolicy&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103950 bfc-',
      ),
      104192 => 
      array (
        'id' => '104192',
        'code' => 'f1-a-tb3621/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء مدينة',
        'menu_name_en' => 'create Acity',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Acity&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104192 bfc-',
      ),
      104193 => 
      array (
        'id' => '104193',
        'code' => 'f1-a-tb3621/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة المدن',
        'menu_name_en' => 'Acitys administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=Acity&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-104193 bfc-',
      ),
      104194 => 
      array (
        'id' => '104194',
        'code' => 'f1-a-tb3621/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح مدينة',
        'menu_name_en' => 'delete Acity',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Acity&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104194 bfc-',
      ),
      104195 => 
      array (
        'id' => '104195',
        'code' => 'f1-a-tb3621/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل مدينة',
        'menu_name_en' => 'display details of Acity',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Acity&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104195 bfc-',
      ),
      104196 => 
      array (
        'id' => '104196',
        'code' => 'f1-a-tb3621/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في المدن',
        'menu_name_en' => 'Acitys search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Acity&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104196 bfc-',
      ),
      104197 => 
      array (
        'id' => '104197',
        'code' => 'f1-a-tb3621/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن مدينة',
        'menu_name_en' => 'Acity quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Acity&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104197 bfc-',
      ),
      104198 => 
      array (
        'id' => '104198',
        'code' => 'f1-a-tb3623/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء acountry.single',
        'menu_name_en' => 'create Acountry',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Acountry&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104198 bfc-',
      ),
      104199 => 
      array (
        'id' => '104199',
        'code' => 'f1-a-tb3623/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة acountry',
        'menu_name_en' => 'Acountrys administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=Acountry&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-104199 bfc-',
      ),
      104200 => 
      array (
        'id' => '104200',
        'code' => 'f1-a-tb3623/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح acountry.single',
        'menu_name_en' => 'delete Acountry',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Acountry&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104200 bfc-',
      ),
      104201 => 
      array (
        'id' => '104201',
        'code' => 'f1-a-tb3623/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل acountry.single',
        'menu_name_en' => 'display details of Acountry',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Acountry&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104201 bfc-',
      ),
      104202 => 
      array (
        'id' => '104202',
        'code' => 'f1-a-tb3623/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في acountry',
        'menu_name_en' => 'Acountrys search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Acountry&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104202 bfc-',
      ),
      104203 => 
      array (
        'id' => '104203',
        'code' => 'f1-a-tb3623/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الاستعلام عن acountry.single',
        'menu_name_en' => 'Acountry quick search',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Acountry&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104203 bfc-',
      ),
      104204 => 
      array (
        'id' => '104204',
        'code' => 'f1-a-tb3623/stats',
        'level' => '999',
        'menu_name_ar' => 'إجراء إحصائيات حول acountry',
        'menu_name_en' => 'Acountrys statistics',
        'page' => 'main.php?Main_Page=afw_mode_stats.php&cl=Acountry&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104204 bfc-',
      ),
      104205 => 
      array (
        'id' => '104205',
        'code' => 'f1-a-tb3622/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة المناطق',
        'menu_name_en' => 'Aregions administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=Aregion&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-104205 bfc-',
      ),
      104206 => 
      array (
        'id' => '104206',
        'code' => 'f1-a-tb3622/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح منطقة',
        'menu_name_en' => 'delete Aregion',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Aregion&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104206 bfc-',
      ),
      104207 => 
      array (
        'id' => '104207',
        'code' => 'f1-a-tb3622/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل منطقة',
        'menu_name_en' => 'display details of Aregion',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Aregion&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104207 bfc-',
      ),
      104208 => 
      array (
        'id' => '104208',
        'code' => 'f1-a-tb3580/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة اجراءات خدمة العملاء',
        'menu_name_en' => 'Crm actions administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=CrmAction&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-104208 bfc-',
      ),
      104209 => 
      array (
        'id' => '104209',
        'code' => 'f1-a-tb3580/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح اجراء خدمة العملاء',
        'menu_name_en' => 'delete Crm action',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=CrmAction&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104209 bfc-',
      ),
      104210 => 
      array (
        'id' => '104210',
        'code' => 'f1-a-tb3580/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل اجراء خدمة العملاء',
        'menu_name_en' => 'display details of Crm action',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=CrmAction&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104210 bfc-',
      ),
    ),
    'sub-folders' => 
    array (
    ),
  ),
);