<?php

	$role_info[324] = array (
  'code' => 'goal-OPERATION',
  'name' => 
  array (
    'ar' => 'الإشراف',
    'en' => 'arole.324',
  ),
  'menu' => 
  array (
    'need_admin' => false,
    'id' => '324',
    'menu_name_ar' => 'الإشراف',
    'menu_name_en' => 'arole.324',
    'page' => 'main.php?Main_Page=fm.php&a=1073&r=324',
    'css' => 'info',
    'icon' => ' icon-324',
    'showme' => true,
    'items' => 
    array (
      104366 => 
      array (
        'id' => '104366',
        'code' => 'workbox',
        'level' => '999',
        'menu_name_ar' => 'صندوق الوارد',
        'menu_name_en' => 'Inbox',
        'page' => 'main.php?Main_Page=workbox.php',
        'css' => 'bf',
        'icon' => 'bficon-104366 bfc-',
      ),
      104502 => 
      array (
        'id' => '104502',
        'code' => 'outbox',
        'level' => '999',
        'menu_name_ar' => 'صندوق الصادر',
        'menu_name_en' => 'Outbox',
        'page' => 'main.php?Main_Page=outbox.php',
        'css' => 'bf',
        'icon' => 'bficon-104502 bfc-',
      ),
      103916 => 
      array (
        'id' => '103916',
        'code' => 'f2-a-crm_customer/qsearch',
        'level' => '999',
        'menu_name_ar' => 'العملاء',
        'menu_name_en' => 'CRM Customer accounts',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=CrmCustomer&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103916 bfc-',
      ),
      103923 => 
      array (
        'id' => '103923',
        'code' => 'f2-a-service/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الخدمات',
        'menu_name_en' => 'Services',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Service&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103923 bfc-',
      ),
      103929 => 
      array (
        'id' => '103929',
        'code' => 'f2-a-service_category/qsearch',
        'level' => '999',
        'menu_name_ar' => 'أصناف الخدمات',
        'menu_name_en' => 'Service categorys',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ServiceCategory&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103929 bfc-',
      ),
      103942 => 
      array (
        'id' => '103942',
        'code' => 'f2-a-crm_orgunit/qsearch',
        'level' => '999',
        'menu_name_ar' => 'جهات متابعة طلبات العملاء',
        'menu_name_en' => 'Crm orgunits',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=CrmOrgunit&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103942 bfc-',
      ),
      104364 => 
      array (
        'id' => '104364',
        'code' => 'f2-a-crm_employee/qsearch',
        'level' => '999',
        'menu_name_ar' => 'المنسقين لدى خدمة العملاء',
        'menu_name_en' => 'Crm employees',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=CrmEmployee&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104364 bfc-',
      ),
      104496 => 
      array (
        'id' => '104496',
        'code' => 'f2-a-response_template/qsearch',
        'level' => '999',
        'menu_name_ar' => 'نماذج الأجوبة',
        'menu_name_en' => 'Response templates',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ResponseTemplate&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104496 bfc-',
      ),
      104498 => 
      array (
        'id' => '104498',
        'code' => 'f2-a-crm_channel/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة قنوات التواصل',
        'menu_name_en' => 'Crm channels administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=CrmChannel&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-104498 bfc-',
      ),
      104604 => 
      array (
        'id' => '104604',
        'code' => 'f2-a-crm_emp_request/qsearch',
        'level' => '1',
        'menu_name_ar' => 'طلبات إستيراد المنسقين من نظام الموارد البشرية',
        'menu_name_en' => 'Crm emp request',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=CrmEmpRequest&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104604 bfc-',
      ),
    ),
    'otherbfs' => 
    array (
      103911 => 
      array (
        'id' => '103911',
        'code' => 'f2-a-crm_customer/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء عميل',
        'menu_name_en' => 'create CRM Customer account',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=CrmCustomer&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103911 bfc-',
      ),
      103912 => 
      array (
        'id' => '103912',
        'code' => 'f2-a-crm_customer/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة العملاء',
        'menu_name_en' => 'CRM Customer accounts administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=CrmCustomer&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103912 bfc-',
      ),
      103913 => 
      array (
        'id' => '103913',
        'code' => 'f2-a-crm_customer/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح عميل',
        'menu_name_en' => 'delete CRM Customer account',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=CrmCustomer&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103913 bfc-',
      ),
      103914 => 
      array (
        'id' => '103914',
        'code' => 'f2-a-crm_customer/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل عميل',
        'menu_name_en' => 'display details of CRM Customer account',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=CrmCustomer&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103914 bfc-',
      ),
      103915 => 
      array (
        'id' => '103915',
        'code' => 'f2-a-crm_customer/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في العملاء',
        'menu_name_en' => 'CRM Customer accounts search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=CrmCustomer&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103915 bfc-',
      ),
      103916 => 
      array (
        'id' => '103916',
        'code' => 'f2-a-crm_customer/qsearch',
        'level' => '999',
        'menu_name_ar' => 'العملاء',
        'menu_name_en' => 'CRM Customer accounts',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=CrmCustomer&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103916 bfc-',
      ),
      103918 => 
      array (
        'id' => '103918',
        'code' => 'f2-a-service/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء خدمة',
        'menu_name_en' => 'create Service',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Service&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103918 bfc-',
      ),
      103919 => 
      array (
        'id' => '103919',
        'code' => 'f2-a-service/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة الخدمات',
        'menu_name_en' => 'Services administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=Service&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103919 bfc-',
      ),
      103920 => 
      array (
        'id' => '103920',
        'code' => 'f2-a-service/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح خدمة',
        'menu_name_en' => 'delete Service',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Service&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103920 bfc-',
      ),
      103921 => 
      array (
        'id' => '103921',
        'code' => 'f2-a-service/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل خدمة',
        'menu_name_en' => 'display details of Service',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Service&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103921 bfc-',
      ),
      103922 => 
      array (
        'id' => '103922',
        'code' => 'f2-a-service/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في الخدمات',
        'menu_name_en' => 'Services search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Service&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103922 bfc-',
      ),
      103923 => 
      array (
        'id' => '103923',
        'code' => 'f2-a-service/qsearch',
        'level' => '999',
        'menu_name_ar' => 'الخدمات',
        'menu_name_en' => 'Services',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Service&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103923 bfc-',
      ),
      103924 => 
      array (
        'id' => '103924',
        'code' => 'f2-a-service_category/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء صنف خدمة',
        'menu_name_en' => 'create Service category',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=ServiceCategory&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103924 bfc-',
      ),
      103925 => 
      array (
        'id' => '103925',
        'code' => 'f2-a-service_category/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة أصناف الخدمات',
        'menu_name_en' => 'Service categorys administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=ServiceCategory&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103925 bfc-',
      ),
      103926 => 
      array (
        'id' => '103926',
        'code' => 'f2-a-service_category/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح صنف خدمة',
        'menu_name_en' => 'delete Service category',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=ServiceCategory&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103926 bfc-',
      ),
      103927 => 
      array (
        'id' => '103927',
        'code' => 'f2-a-service_category/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل صنف خدمة',
        'menu_name_en' => 'display details of Service category',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=ServiceCategory&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103927 bfc-',
      ),
      103928 => 
      array (
        'id' => '103928',
        'code' => 'f2-a-service_category/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في أصناف الخدمات',
        'menu_name_en' => 'Service categorys search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=ServiceCategory&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103928 bfc-',
      ),
      103929 => 
      array (
        'id' => '103929',
        'code' => 'f2-a-service_category/qsearch',
        'level' => '999',
        'menu_name_ar' => 'أصناف الخدمات',
        'menu_name_en' => 'Service categorys',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ServiceCategory&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103929 bfc-',
      ),
      103937 => 
      array (
        'id' => '103937',
        'code' => 'f2-a-crm_orgunit/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء جهة متابعة',
        'menu_name_en' => 'create Crm orgunit',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=CrmOrgunit&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103937 bfc-',
      ),
      103938 => 
      array (
        'id' => '103938',
        'code' => 'f2-a-crm_orgunit/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة جهات متابعة طلبات العملاء',
        'menu_name_en' => 'Crm orgunits administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=CrmOrgunit&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-103938 bfc-',
      ),
      103939 => 
      array (
        'id' => '103939',
        'code' => 'f2-a-crm_orgunit/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح جهة متابعة',
        'menu_name_en' => 'delete Crm orgunit',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=CrmOrgunit&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103939 bfc-',
      ),
      103940 => 
      array (
        'id' => '103940',
        'code' => 'f2-a-crm_orgunit/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل جهة متابعة',
        'menu_name_en' => 'display details of Crm orgunit',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=CrmOrgunit&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103940 bfc-',
      ),
      103941 => 
      array (
        'id' => '103941',
        'code' => 'f2-a-crm_orgunit/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في جهات متابعة طلبات العملاء',
        'menu_name_en' => 'Crm orgunits search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=CrmOrgunit&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103941 bfc-',
      ),
      103942 => 
      array (
        'id' => '103942',
        'code' => 'f2-a-crm_orgunit/qsearch',
        'level' => '999',
        'menu_name_ar' => 'جهات متابعة طلبات العملاء',
        'menu_name_en' => 'Crm orgunits',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=CrmOrgunit&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-103942 bfc-',
      ),
      104359 => 
      array (
        'id' => '104359',
        'code' => 'f2-a-crm_employee/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء منسق',
        'menu_name_en' => 'create Crm employee',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=CrmEmployee&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104359 bfc-',
      ),
      104360 => 
      array (
        'id' => '104360',
        'code' => 'f2-a-crm_employee/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة المنسقين لدى خدمة العملاء',
        'menu_name_en' => 'Crm employees administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=CrmEmployee&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-104360 bfc-',
      ),
      104361 => 
      array (
        'id' => '104361',
        'code' => 'f2-a-crm_employee/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح منسق',
        'menu_name_en' => 'delete Crm employee',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=CrmEmployee&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104361 bfc-',
      ),
      104362 => 
      array (
        'id' => '104362',
        'code' => 'f2-a-crm_employee/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل منسق',
        'menu_name_en' => 'display details of Crm employee',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=CrmEmployee&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104362 bfc-',
      ),
      104363 => 
      array (
        'id' => '104363',
        'code' => 'f2-a-crm_employee/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في المنسقين لدى خدمة العملاء',
        'menu_name_en' => 'Crm employees search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=CrmEmployee&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104363 bfc-',
      ),
      104364 => 
      array (
        'id' => '104364',
        'code' => 'f2-a-crm_employee/qsearch',
        'level' => '999',
        'menu_name_ar' => 'المنسقين لدى خدمة العملاء',
        'menu_name_en' => 'Crm employees',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=CrmEmployee&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104364 bfc-',
      ),
      104366 => 
      array (
        'id' => '104366',
        'code' => 'workbox',
        'level' => '999',
        'menu_name_ar' => 'صندوق الوارد',
        'menu_name_en' => 'Inbox',
        'page' => 'main.php?Main_Page=workbox.php',
        'css' => 'bf',
        'icon' => 'bficon-104366 bfc-',
      ),
      104491 => 
      array (
        'id' => '104491',
        'code' => 'f2-a-response_template/edit',
        'level' => '999',
        'menu_name_ar' => 'إنشاء نموذج إجابة',
        'menu_name_en' => 'create Response template',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=ResponseTemplate&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104491 bfc-',
      ),
      104492 => 
      array (
        'id' => '104492',
        'code' => 'f2-a-response_template/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة نماذج الأجوبة',
        'menu_name_en' => 'Response templates administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=ResponseTemplate&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-104492 bfc-',
      ),
      104493 => 
      array (
        'id' => '104493',
        'code' => 'f2-a-response_template/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح نموذج إجابة',
        'menu_name_en' => 'delete Response template',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=ResponseTemplate&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104493 bfc-',
      ),
      104494 => 
      array (
        'id' => '104494',
        'code' => 'f2-a-response_template/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل نموذج إجابة',
        'menu_name_en' => 'display details of Response template',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=ResponseTemplate&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104494 bfc-',
      ),
      104495 => 
      array (
        'id' => '104495',
        'code' => 'f2-a-response_template/search',
        'level' => '999',
        'menu_name_ar' => 'البحث في نماذج الأجوبة',
        'menu_name_en' => 'Response templates search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=ResponseTemplate&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104495 bfc-',
      ),
      104496 => 
      array (
        'id' => '104496',
        'code' => 'f2-a-response_template/qsearch',
        'level' => '999',
        'menu_name_ar' => 'نماذج الأجوبة',
        'menu_name_en' => 'Response templates',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ResponseTemplate&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104496 bfc-',
      ),
      104498 => 
      array (
        'id' => '104498',
        'code' => 'f2-a-crm_channel/qedit',
        'level' => '999',
        'menu_name_ar' => 'إدارة قنوات التواصل',
        'menu_name_en' => 'Crm channels administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=CrmChannel&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-104498 bfc-',
      ),
      104499 => 
      array (
        'id' => '104499',
        'code' => 'f2-a-crm_channel/delete',
        'level' => '999',
        'menu_name_ar' => 'مسح قناة تواصل',
        'menu_name_en' => 'delete Crm channel',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=CrmChannel&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104499 bfc-',
      ),
      104500 => 
      array (
        'id' => '104500',
        'code' => 'f2-a-crm_channel/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل قناة تواصل',
        'menu_name_en' => 'display details of Crm channel',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=CrmChannel&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104500 bfc-',
      ),
      104502 => 
      array (
        'id' => '104502',
        'code' => 'outbox',
        'level' => '999',
        'menu_name_ar' => 'صندوق الصادر',
        'menu_name_en' => 'Outbox',
        'page' => 'main.php?Main_Page=outbox.php',
        'css' => 'bf',
        'icon' => 'bficon-104502 bfc-',
      ),
      104596 => 
      array (
        'id' => '104596',
        'code' => 'f2-a-crm_channel/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء قناة تواصل',
        'menu_name_en' => 'create Crm channel',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=CrmChannel&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104596 bfc-',
      ),
      104597 => 
      array (
        'id' => '104597',
        'code' => 'f2-a-crm_channel/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في قنوات التواصل',
        'menu_name_en' => 'Crm channels search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=CrmChannel&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104597 bfc-',
      ),
      104598 => 
      array (
        'id' => '104598',
        'code' => 'f2-a-crm_channel/qsearch',
        'level' => '1',
        'menu_name_ar' => 'قنوات التواصل',
        'menu_name_en' => 'Crm channels',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=CrmChannel&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104598 bfc-',
      ),
      104599 => 
      array (
        'id' => '104599',
        'code' => 'f2-a-crm_emp_request/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء طلب إستيراد منسق',
        'menu_name_en' => 'create Crm emp request',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=CrmEmpRequest&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104599 bfc-',
      ),
      104600 => 
      array (
        'id' => '104600',
        'code' => 'f2-a-crm_emp_request/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة طلبات إستيراد المنسقين من نظام الموارد البشرية',
        'menu_name_en' => 'Crm emp request administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=CrmEmpRequest&currmod=crm&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-104600 bfc-',
      ),
      104601 => 
      array (
        'id' => '104601',
        'code' => 'f2-a-crm_emp_request/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح طلب إستيراد منسق',
        'menu_name_en' => 'delete Crm emp request',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=CrmEmpRequest&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104601 bfc-',
      ),
      104602 => 
      array (
        'id' => '104602',
        'code' => 'f2-a-crm_emp_request/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل طلب إستيراد منسق',
        'menu_name_en' => 'display details of Crm emp request',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=CrmEmpRequest&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104602 bfc-',
      ),
      104603 => 
      array (
        'id' => '104603',
        'code' => 'f2-a-crm_emp_request/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في طلبات إستيراد المنسقين من نظام الموارد البشرية',
        'menu_name_en' => 'Crm emp request search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=CrmEmpRequest&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104603 bfc-',
      ),
      104604 => 
      array (
        'id' => '104604',
        'code' => 'f2-a-crm_emp_request/qsearch',
        'level' => '1',
        'menu_name_ar' => 'طلبات إستيراد المنسقين من نظام الموارد البشرية',
        'menu_name_en' => 'Crm emp request',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=CrmEmpRequest&currmod=crm',
        'css' => 'bf',
        'icon' => 'bficon-104604 bfc-',
      ),
    ),
    'sub-folders' => 
    array (
    ),
  ),
);